fail_fast: false
exclude: |
    (?x)^(
      .*\b(migrations)\b.*|
      .*\b(__pycache__)\b.*|
      .*\b(.git)\b.*
    )$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=4"
          - "--no-sort-keys"
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [
          --branch, master,
        ]

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies:
          - Flake8-pyproject
        exclude: .*\b(__init__)\b.*
