version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: scot
      POSTGRES_PASSWORD: tiger
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
