version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: scot
      POSTGRES_PASSWORD: tiger
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

#  web:
#    build: .
#    restart: always
#    ports:
#      - "5000:5000"
#    environment:
#      DATABASE_URL: postgresql://postgres:example@db:5432/test_db
