"""FIX_table_products

Revision ID: 44363c4c0f6a
Revises: 9da0b45f8807
Create Date: 2023-12-01 23:55:15.670893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44363c4c0f6a'
down_revision = '9da0b45f8807'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_name_key', 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('products_name_key', 'products', ['name'])
    # ### end Alembic commands ###
