"""create new table "news"

Revision ID: 9da0b45f8807
Revises: 7dd8a8a8aa45
Create Date: 2023-07-11 23:04:56.556066

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '9da0b45f8807'
down_revision = '7dd8a8a8aa45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'news',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('publication_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('author_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['author_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_table('news')
    # ### end Alembic commands ###
