"""first

Revision ID: bef6b1d36074
Revises:
Create Date: 2023-06-28 14:12:53.463249

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'bef6b1d36074'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_products_id', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_payments_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_order_history_id', table_name='order_history')
    op.drop_table('order_history')
    op.drop_index('ix_orders_id', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'orders',
        sa.Column(
            'id',
            sa.INTEGER(),
            server_default=sa.text("nextval('orders_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            'order_date',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='orders_user_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='orders_pkey'),
        postgresql_ignore_search_path=False,
    )
    op.create_index('ix_orders_id', 'orders', ['id'], unique=False)
    op.create_table(
        'order_history',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_history_order_id_fkey'),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='order_history_product_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='order_history_pkey'),
    )
    op.create_index('ix_order_history_id', 'order_history', ['id'], unique=False)
    op.create_table(
        'payments',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            'payment_date',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column('payment_amount', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='payments_order_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='payments_pkey'),
    )
    op.create_index('ix_payments_id', 'payments', ['id'], unique=False)
    op.create_table(
        'products',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
        sa.Column('description', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
        sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='products_pkey'),
        sa.UniqueConstraint('name', name='products_name_key'),
    )
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    op.create_table(
        'users',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
        sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
        sa.Column('password_hash', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
        sa.Column(
            'time_created',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='users_pkey'),
        sa.UniqueConstraint('email', name='users_email_key'),
        sa.UniqueConstraint('username', name='users_username_key'),
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    # ### end Alembic commands ###
